package com.example.chat_app;

import android.content.Context;
import android.content.SharedPreferences;

import com.example.chat_app.rsa.RSAKeyPairGenerator;
import com.example.chat_app.rsa.RSAUtils;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseAuthException;


import org.junit.Test;

import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;


import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;

import static com.example.chat_app.rsa.RSAUtils.encrypt;
import static org.junit.Assert.*;

/**
 * Example local unit test, which will execute on the development machine (host).
 *
 * @see <a href="http://d.android.com/tools/testing">Testing documentation</a>
 */
public class ExampleUnitTest {
    private static String publicKey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCysnQLRLpZez0Vxyqy+qIRVDYzsogU2F8duVj/Je5nEY62N+ubXeKuLXOPzcaBnNTv8HGVUYKaF77az7oyzB2Ek6pP0MFyCgLzGaEEgrDH/VB+TpDbRMF29jDiRH1zqy0OVdkl1BZFxcLisoxjlrsd0oVBTCh+znLMFfpsoJVDFwIDAQAB";
    private static String privateKey = "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALKydAtEull7PRXHKrL6ohFUNjOyiBTYXx25WP8l7mcRjrY365td4q4tc4/NxoGc1O/wcZVRgpoXvtrPujLMHYSTqk/QwXIKAvMZoQSCsMf9UH5OkNtEwXb2MOJEfXOrLQ5V2SXUFkXFwuKyjGOWux3ShUFMKH7OcswV+myglUMXAgMBAAECgYAp+WTsqK4lCp+kl+3dsKWU8HTy28K/MrvU3Y6cECrZpvQgtS3whrMSOrbkVm+ETnRuD8p+SnElBOLdvuF7wRpFf2uMD5lJmXy3cCEFybqUhPvF/t5aBXJoPV7NZUGGfxi1QvqYfRPvtYyXaAuwv5X0ZIb93EaSnBWuuxgSmSYgkQJBANxlI/rF17HQ5aR061QPbqMKdKpFz+cse9NzC0SMDX+vaw4iznhpKzM4OTPY0PFn3H+WnzGdd01L6utKWjw4GfUCQQDPkM/8m7H6snx27We6pcS45IEADQiTOQXqYd0vY6Z73AXd+2Wyzz+ZWtocKv7JAE5Jh6eajXFK7wXfX9rC8UVbAkBJT7twJ29gTsSUt++vvpJm2YuFOEO3+iwWYiZVXuD+oDNUOG/FzfX4y7L7dBvMsWe/aTL7Jg4RQDecnNb3QRIhAkEAv/eqpHJK1RWmT0eaG+GcY3PSav2i5KZkdjU0n9OF8h+3vWn40LskkuyXtF1/bt69iPvRYvtVwHv37nN0m78Q6QJBALAsXLYI+yypU7HN9x/bMgveYXlgyzf9bSYzUz66A87gwDQx2FFi4F0PrrLnisx6ibzb8w4eYM4CHn1LTlf5olk=";

    @Test
    public void addition_isCorrect() throws NoSuchAlgorithmException, IllegalBlockSizeException, InvalidKeyException, NoSuchPaddingException, BadPaddingException, FirebaseAuthException {

        //MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMoI5zWLWhuFw1zUpvETg5ov6fi02ESpBbabbVCtp4UJklNuM0cLEpC0e/OO/TsCe6Qnzne0wpXAl3/LzqwwinAuY9G++lKi5Cs1GY7Cx8RrzMKb8Y0Vurcd3ajb22XjGzynyddqsZ8LMQjaYbsliIo7tZPI33dfiRCWhvPgE247AgMBAAECgYAKVCsx3xZzusJyoAKK56L+Qn3VM7WsyPFcVRThH4elcwhSkJs5ghToZfnCSWij2CwnB8vz7b9W9ZopM+u0fOTO4RjEa95G/Mf7ls799iS3UYr6ltLvCyC/Tkt73UWhQiZBX2xdDkB5m1xXCwDu+y9vaZa3zdtdjnE90Qs1yFPGwQJBAPPibfB6slQ6awAShSzpABVatU6xdFsooOJ4Z/xx7f4v6EKXcZg0I8XISC+YgJ+fFJ4pH4ovDB70rSL+9WKf7fsCQQDUEkFWQfooKA+IdQrMLoACrmcrvo87BqZoaj7xZ/ng6Cg3+/93hp92UDvFHCF9qpuMpyDNofwYcYb/KX4WB8zBAkBE9bqGa/suq9IDlDkJ6Nw4LYzksnKnMAbF4qvsir5zyFIROkdJdTzEOQyIQMPl3pJy4kfjx8fSnPaz1YnHGFevAkEAj8FEKv2UXm4xgVWdmSUYPzkL1LpbCy8J1JPY0PmjiBK3WKPo25QVOjVPHuFfzni88o5EDUB1y/gBA6yTvMlSwQJADfLUkNHsTOa/m1gqvEpRZ8lOMrb8gq5tBDWUhHUANQ+75dkKnQNpuYN4RbDoo55WoYqA8id83Mo8ZM7f1SSAEg==

        String receiverPrivateKey="MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJmujUXRGyWkqZ+1d241yRYPMxnYCkP0I/pg1iG03DyXuxvjSDlIZF0rpTwKAmm7HjDx4n1buqsd96idmFtc7+ywySVg9hFtVmtL5552nqL7s0yKxzrmUH7LEaxJBSmIdoAyquny3qwzxSBSLbZJGBnt7Gmx7vaGeTwzMNgrGUI3AgMBAAECgYAOaUS5XB2xLse/pw/g0Q2SRZdp82bDCI0Qvy2IhTuoOViqcAQnZ8p0xWr+Cx8Lmyhk0cns+qhLWfwNxV/lvi+69Qrn9LxDwN4xeUfkTr9+6TkMCUT7pv3PPgPtmPJdPr2jHWocQGhbwxBZpalms+T6RyfXPMjTig/eI/fG54s4gQJBANPHJSkyV7CdUMQ+FimZJp4+RkCtO71s1rWamnwjUZoPpP0JAocDYW1V5Kdjzzw7qOxZ0ANiYSCGyCfRcgrW9s8CQQC5xc7pitpyulbNhT4LJZMyIwbcBWWiVIAzl4KzfYuBT2KUlwmS/NfLunvd2S7xtv52uHUZQIXy1ckhDcRlfFgZAkEAw8XNLJBFUBedmkxq4HmboZ2gBBogp7P9qFQLi8Z6oRjlRKUXmQgfAJvujG9QHDZqqlM8YGSJtS/jyCtuaWbfMQJAToNtaYLHxElAumefyzI8PapUEdUuGSdBb4yPLrDWrvYQIeCbqUW3JmFQTHinwHyomyBmTR/Z/MGh2Zhp8sJUsQJBAIQsOOvQZGzh8xzgfbAADH9OcV1Isd8anl6poW8STXMBIfUZqZIHbm9ZHlCkWVkBIdhpVjcD0Z8W/NlZUVS0P/c=";
        String senderPrivateKey="MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKMnQLYvMKSvGxkc36l9BiU8uK3yaVSD1iABcpVJsICUaUOdKHmq+lfxT2NKt/sNlplpepFefDXlDieiRPK3ayD4PKJUFN7eI+7lAV11Wbpy4Lp2S1kSUy3ps80uYqJVaanjJEveaLdTzvVc8Tv7pzygoph+23fEaVhAa7mGgsWPAgMBAAECgYAvLKrf4q4wd/cgYEJlieJsgu2tUiHVj5cqwvBkLR3tV7xGEhuBbogbRIldXt3qp+erLR4FCWpl1PiuShOgkJtXQ24kJ7zAmQgw7Mi1a9CRVd9b3H/keeN3AwA5flqlYguOtfjgVXCzpUiRRnrQx4IaOxfLz80CIlXgm8wvWC/fDQJBAM6lzYo6OSZ/inAhQWE4kHM0YumRkmiuFREcnnrFT36QVw1IZQ9YZNGNqyD83YTiFJKetJYpmeoxPP4ELsVNSeUCQQDKHkHHXOHMI5lr1fDhoznCKw1Su3qDFt6SqWZyqJZfAZJq+gfV5HLgw+gbTPfY8+PBHkTfbEJi2uJhs8SZB0pjAkBYH8Tjaajtjf5Pix8Cgsi3GGQGDxpModBCF95NpM8dvhghhfny7VMxOiT8UFl3TaJQVHXWg68rfAvyl34KjccxAkEAtvKmRcecFsSOZZ6UWBj/+fIwMBfE8A1uT8CIG/bfjYWFu9Ev8HrFRQ/u82861KUGHdLBMp7yhDpuOVOX+5Au0wJAccwO08Afw7OG8CebTihYK8HhFSclhjXYYmkDxgwHVooQfhehBOAZJxgdBIxfTwpB/DNlvOf8j58nrs0L9/QDJQ==";
        String receiverPublicKey="MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZpGUEjVmcEwOGvCH1XzKj18vmMqwfWj0UJ/H/0iZq07+EIy08hX78k2KgMlyDcBCJDbwB3MySg39UDHG6lCpCAp2c71FIvlhz/deX8ECqtkOkeS+n/SIWzUO/lACNur2gsKvowwiJ9vt1jpHRoHJogG1x1xd+f10dQDwLtGZ+wwIDAQAB";

        String encryptedString = Base64.getEncoder().encodeToString(encrypt("Hello Zahit!", receiverPublicKey));
        System.out.println("Cipher Text: "+encryptedString);
        String decryptedString = RSAUtils.decrypt(encryptedString,receiverPrivateKey);
        System.out.println(decryptedString);



    }
    @Test
    public void addition_isCorrect2() throws NoSuchAlgorithmException, IllegalBlockSizeException, InvalidKeyException, NoSuchPaddingException, BadPaddingException, FirebaseAuthException {




    }
}